### PR TITLE
Added footer

### LINKED ISSUE #16: Suggestions
Open for suggestions do propose for anything which can be better In website and you can do it like adding some feature or changing something
live link (https://study-notion-frontend-wheat.vercel.app/

### PR DESCRIPTION
**Pull request by Vansh-Narang**
fixes #16

### CODE REVIEW

**Comment by Horror26** [comment]
why you are changing server.js and packge.json no need to change it

**Comment by Horror26** [comment]
and sorry for trouble make pr on <16-suggestions-footer> branch

**Comment by Horror26** [comment]
other than that footer looks good

**Comment by Vansh-Narang** [comment]
There is no change in server or index.js I have only updated the packages and some adjust some spacing no changes are there which may effect the working

**Comment by Horror26** [comment]
> There is no change in server or index.js I have only updated the packages and some adjust some spacing no changes are there which may effect the working

ok please make pr on <16-suggestions-footer> branch

**Pull request closed without merging**
