### PR TITLE
hover effect added !!

### LINKED ISSUE #23: Add hover effect in each card
## What ?

I would like to add hover effect on each card showing free courses. the hover style will be consistent among all cards. tha hover style which i will adapt for it will be the first card current style.

## Screenshots

image

## Code of Conduct

- [x] I agree to follow this project's Code of Conduct

<br>

> **Kindly assign it to me under _HacktoberFest'23_** 
> **I will surely complete it ASAP**

### PR DESCRIPTION
**Pull request by AKACHI-4**
## Fixes Issue

Closes #23 

## Changes proposed

In the **CourseCard** component, I added the transition for hovering over cards.

## Screenshots

image

_Hey @Horror26, Kindly review my PR and suggest further changes if any.._ 

_if no further changes kindly accept it under **hacktoberfest-accepted**_

### CODE REVIEW

**Comment by Horror26** [comment]
looks good 
but sorry for trouble make [r with base branch 23-add-hover-effect-in-each-card
if any issues for fetching branch  try this 
git fetch origin
git checkout 23-add-hover-effect-in-each-card

**Comment by AKACHI-4** [comment]
okay yah lemme do changes .

**Comment by AKACHI-4** [comment]
so I think i've to make a different pr right and close this one.. ?

**Comment by AKACHI-4** [comment]
yah got it know what to do ..

**Comment by AKACHI-4** [comment]
thanks u

**Pull request closed without merging**
